ALTER TABLE public."Table" 
ALTER COLUMN GrAppv TYPE NUMERIC 
USING CAST(REPLACE(REPLACE(GrAppv, '$', ''), ',', '') AS NUMERIC);

ALTER TABLE public."Table" 
ALTER COLUMN SBA_Appv TYPE NUMERIC 
USING CAST(REPLACE(REPLACE(SBA_Appv, '$', ''), ',', '') AS NUMERIC);

